server:
  port: ${APP_PORT:8080}
  address: ${APP_HOST:0.0.0.0}

spring:
  application:
    name: ${APP_NAME:messaging-apache-kafka}
    env_file: .env

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      fail-fast: ${KAFKA_ADMIN_FAIL_FAST:true}

    # ---------- Producer ----------
    producer:
      acks: ${KAFKA_PRODUCER_ACKS:all}
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      properties:
        enable.idempotence: ${KAFKA_ENABLE_IDEMPOTENCE:true}
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT_MS:120000}
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS:30000}
        linger.ms: ${KAFKA_LINGER_MS:0}
        batch.size: ${KAFKA_BATCH_SIZE:16384}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # ---------- Consumer ----------
    consumer:
      group-id: ${KAFKA_GROUP_ID:main-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      enable-auto-commit: ${KAFKA_ENABLE_AUTO_COMMIT:true}
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:500}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    # ---------- Listener (consumer runtime behavior) ----------
    listener:
      concurrency: ${KAFKA_LISTENER_CONCURRENCY:1}
      ack-mode: ${KAFKA_ACK_MODE:record}


app:
  kafka:
    topic: ${KAFKA_TOPIC_NAME:main-topic}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.apache.kafka: ${LOG_LEVEL_KAFKA:WARN}
    org.springframework.kafka: ${LOG_LEVEL_SPRING_KAFKA:INFO}

